apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.frontendv1.replicas }}


  selector:
    matchLabels:
      app: frontend
      version: v1

  template:
    metadata:
      labels:
        app: frontend
        version: v1

    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontendv1.image }}
        imagePullPolicy: Always

        ports:
        - containerPort: {{ .Values.frontendv1.port }}

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"  

        readinessProbe:
          httpGet:
            path: /
            port: 80

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 80

          initialDelaySeconds: 15
          periodSeconds: 20            
