apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-canary
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "20"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
       - weather-local
      secretName: weather-tls

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: frontendv2-service
                port:
                  number: 80
