namespace: weather-app

frontend:
  replicas: 2
  image: nilesh9168/frontend-weather:latest
  port: 80

backend:
  replicas: 2
  image: nilesh9168/backend-weather:latest
  port: 5000  

service:
  frontendPort: 80
  backendPort: 5000

ingress:
  enabled: true
  host: weather-local