name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello Nilesh"

  docker: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Print username
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: print Password  
        run: echo ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          docker build \
           -t ${{ secrets.DOCKER_USERNAME }}/frontend_weather:latest \
           -t ${{ secrets.DOCKER_USERNAME }}/frontend_weather:${{ github.sha }} \
           ./Frontend_app

      - name: push frontend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_weather:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_weather:${{ github.sha }}     

      - name: Build backend image
        run: |
          docker build \
           -t ${{ secrets.DOCKER_USERNAME }}/backend_weather:latest \
           -t ${{ secrets.DOCKER_USERNAME }}/backend_weather:${{ github.sha }} \
          ./backend_app

      - name: push backend image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_weather:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_weather:${{ github.sha}}
  
  deploy:
    runs-on: self-hosted
    
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4    
          
      - name: verify files
        run: |
          pwd
          ls -lag
          ls -la k8s

      # - name: create namespace
      #   run: kubectl apply -f k8s/namespace.yaml
            
      # - name: Deploy manifests
      #   run: kubectl apply -f k8s/

      - name: Deploy manifests
        run: |
          helm upgrade --install weather-release ./helm/weather-app \
          -n weather-app \
          --create-namespace
          

      - name: Restart rollout
        run: |
          kubectl rollout restart deployment/frontend -n weather-app
          kubectl rollout restart deployment/backend -n weather-app
          
      - name: wait for rollout
        run: | 
          kubectl rollout status deployment/frontend -n weather-app
          kubectl rollout status deployment/backend -n weather-app
          
      - name: Verify
        run: |
          kubectl get pods -n weather-app
          kubectl get svc -n weather-app     